# https://www.lewagon.com/blog/tuto-setup-metatags-rails
meta_title: "TODO"
meta_description: "TODO"
meta_image: "TODO" # image from app/assets/images/
twitter_account: "@TODO" # Needed for Twitter Cards
